# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pico_vna.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pico_vna.proto',
  package='picogrpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0epico_vna.proto\x12\x08picogrpc\"%\n\tDataPoint\x12\x0c\n\x04real\x18\x01 \x01(\x02\x12\n\n\x02im\x18\x02 \x01(\x02\"*\n\x0bScanRequest\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0c\n\x04stop\x18\x02 \x01(\x05\"h\n\tScanReply\x12\r\n\x05\x66reqs\x18\x01 \x03(\x02\x12%\n\x08s11_data\x18\x02 \x03(\x0b\x32\x13.picogrpc.DataPoint\x12%\n\x08s21_data\x18\x03 \x03(\x0b\x32\x13.picogrpc.DataPoint2G\n\x08PicoGrpc\x12;\n\x0bRequestScan\x12\x15.picogrpc.ScanRequest\x1a\x13.picogrpc.ScanReply\"\x00\x62\x06proto3'
)




_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='picogrpc.DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='picogrpc.DataPoint.real', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='im', full_name='picogrpc.DataPoint.im', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=65,
)


_SCANREQUEST = _descriptor.Descriptor(
  name='ScanRequest',
  full_name='picogrpc.ScanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='picogrpc.ScanRequest.start', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop', full_name='picogrpc.ScanRequest.stop', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=109,
)


_SCANREPLY = _descriptor.Descriptor(
  name='ScanReply',
  full_name='picogrpc.ScanReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='freqs', full_name='picogrpc.ScanReply.freqs', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='s11_data', full_name='picogrpc.ScanReply.s11_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='s21_data', full_name='picogrpc.ScanReply.s21_data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=215,
)

_SCANREPLY.fields_by_name['s11_data'].message_type = _DATAPOINT
_SCANREPLY.fields_by_name['s21_data'].message_type = _DATAPOINT
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['ScanRequest'] = _SCANREQUEST
DESCRIPTOR.message_types_by_name['ScanReply'] = _SCANREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), {
  'DESCRIPTOR' : _DATAPOINT,
  '__module__' : 'pico_vna_pb2'
  # @@protoc_insertion_point(class_scope:picogrpc.DataPoint)
  })
_sym_db.RegisterMessage(DataPoint)

ScanRequest = _reflection.GeneratedProtocolMessageType('ScanRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCANREQUEST,
  '__module__' : 'pico_vna_pb2'
  # @@protoc_insertion_point(class_scope:picogrpc.ScanRequest)
  })
_sym_db.RegisterMessage(ScanRequest)

ScanReply = _reflection.GeneratedProtocolMessageType('ScanReply', (_message.Message,), {
  'DESCRIPTOR' : _SCANREPLY,
  '__module__' : 'pico_vna_pb2'
  # @@protoc_insertion_point(class_scope:picogrpc.ScanReply)
  })
_sym_db.RegisterMessage(ScanReply)



_PICOGRPC = _descriptor.ServiceDescriptor(
  name='PicoGrpc',
  full_name='picogrpc.PicoGrpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=217,
  serialized_end=288,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestScan',
    full_name='picogrpc.PicoGrpc.RequestScan',
    index=0,
    containing_service=None,
    input_type=_SCANREQUEST,
    output_type=_SCANREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PICOGRPC)

DESCRIPTOR.services_by_name['PicoGrpc'] = _PICOGRPC

# @@protoc_insertion_point(module_scope)
