# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pico_vna_pb2 as pico__vna__pb2


class PicoGrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestScan = channel.unary_unary(
        '/picogrpc.PicoGrpc/RequestScan',
        request_serializer=pico__vna__pb2.ScanRequest.SerializeToString,
        response_deserializer=pico__vna__pb2.ScanReply.FromString,
        )


class PicoGrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RequestScan(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PicoGrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestScan': grpc.unary_unary_rpc_method_handler(
          servicer.RequestScan,
          request_deserializer=pico__vna__pb2.ScanRequest.FromString,
          response_serializer=pico__vna__pb2.ScanReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'picogrpc.PicoGrpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
