# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pico_vna.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pico_vna.proto',
  package='picogrpc',
  syntax='proto3',
  serialized_options=b'\242\002\003HLW',
  serialized_pb=b'\n\x0epico_vna.proto\x12\x08picogrpc\"%\n\tDataPoint\x12\x0c\n\x04real\x18\x01 \x01(\x02\x12\n\n\x02im\x18\x02 \x01(\x02\"\r\n\x0b\x44\x61taRequest\".\n\tDataReply\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.picogrpc.DataPoint2G\n\x08PicoGrpc\x12;\n\x0bRequestData\x12\x15.picogrpc.DataRequest\x1a\x13.picogrpc.DataReply\"\x00\x42\x06\xa2\x02\x03HLWb\x06proto3'
)




_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='picogrpc.DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='real', full_name='picogrpc.DataPoint.real', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='im', full_name='picogrpc.DataPoint.im', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=65,
)


_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='picogrpc.DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=80,
)


_DATAREPLY = _descriptor.Descriptor(
  name='DataReply',
  full_name='picogrpc.DataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='picogrpc.DataReply.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=128,
)

_DATAREPLY.fields_by_name['data'].message_type = _DATAPOINT
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['DataReply'] = _DATAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), {
  'DESCRIPTOR' : _DATAPOINT,
  '__module__' : 'pico_vna_pb2'
  # @@protoc_insertion_point(class_scope:picogrpc.DataPoint)
  })
_sym_db.RegisterMessage(DataPoint)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'pico_vna_pb2'
  # @@protoc_insertion_point(class_scope:picogrpc.DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)

DataReply = _reflection.GeneratedProtocolMessageType('DataReply', (_message.Message,), {
  'DESCRIPTOR' : _DATAREPLY,
  '__module__' : 'pico_vna_pb2'
  # @@protoc_insertion_point(class_scope:picogrpc.DataReply)
  })
_sym_db.RegisterMessage(DataReply)


DESCRIPTOR._options = None

_PICOGRPC = _descriptor.ServiceDescriptor(
  name='PicoGrpc',
  full_name='picogrpc.PicoGrpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=130,
  serialized_end=201,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestData',
    full_name='picogrpc.PicoGrpc.RequestData',
    index=0,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_DATAREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PICOGRPC)

DESCRIPTOR.services_by_name['PicoGrpc'] = _PICOGRPC

# @@protoc_insertion_point(module_scope)
